### ISSUE TITLE
"python3 setup.py test" gives "RuntimeError: Explicitly using 'twisted' already"

### ISSUE THREAD

**Issue by shlomif** [crossbario/txaio#165]
```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing txaio.egg-info/PKG-INFO
writing dependency_links to txaio.egg-info/dependency_links.txt
writing requirements to txaio.egg-info/requires.txt
writing top-level names to txaio.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'txaio.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 250, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/shlomif/Download/unpack/to-del/txaio/txaio/with_asyncio.py", line 29, in <module>
    txaio.use_asyncio()
  File "/home/shlomif/Download/unpack/to-del/txaio/txaio/__init__.py", line 122, in use_asyncio
    raise RuntimeError("Explicitly using '{}' already".format(_explicit_framework))
RuntimeError: Explicitly using 'twisted' already
```

I'm on mageia linux x86-64 v8. with python3-3.8.5-1.mga8

**Comment by oberstet** [comment]
txaio is tested using tox, eg have a look here https://github.com/crossbario/txaio/blob/master/tox.ini or try `tox -e py38-asyncio`

**Comment by shlomif** [comment]
Thanks, @oberstet ! `tox` seems to be working, but I think the `setup.py test` failure message can be made much more brief (the first line scrolled past my console viewport).

**Comment by oberstet** [comment]
> Explicitly using 'twisted' already

not sure how to make the message more useful .. maybe "Cannot select 'asyncio' :  'twisted' was already selected" ..

note: the actual reason it fails in this case is: the unit tests expect an environment variable to be set to select the framework - this way we can use the same unit test code for both
