### ISSUE TITLE
Complain if you explicitly set the "other" framework

### ISSUE THREAD

**Issue by meejah** [crossbario/txaio#42]
Currently, if you call ``.use_twisted()`` and then later call ``.use_asyncio()`` txaio will merrily swap out for the asyncio methods.

It should be an error if you explicitly call ``.use_twisted()`` and ``.use_asyncio()`` in the same process (but not, e.g., if Twisted was auto-selected but you call .use_asyncio() explicitly nor if you call .use_asyncio() > 1 time).

See also https://github.com/crossbario/autobahn-python/issues/547

**Comment by oberstet** [comment]
There should not be auto-selection at all. Can we turn that off? A user MUST select one backend explicitly in a given program/process exactly once.

**Comment by meejah** [comment]
Yes, we could turn it off...but then do we raise an exception on any API call if you *haven't* called ``use_*()`` yet?

FWIW, I don't believe the auto-selection was the issue in the original Autobahn bug -- I suspect it was something to do with importing from both ``autobahn.twisted.*`` and ``autobahn.asyncio.*`` in the same process.

**Comment by wirebirdlabs** [comment]
It's possible that this change broke Autobahn TestSuite -- here's the related issue in that repository: https://github.com/crossbario/autobahn-testsuite/issues/55

**Comment by meejah** [comment]
There are fixes in autobahn for the txaio changes (dd1cff8f9480a125e510108482bfaf5b9eedc916) which aren't yet in an Autobahn release... (cc @oberstet)

**Comment by wirebirdlabs** [comment]
Indeed: https://github.com/crossbario/autobahn-python/commit/dd1cff8f9480a125e510108482bfaf5b9eedc916

Here's the 1-liner fix I figured could fix the TestSuite, and didn't realizing it was forcing your hands on releasing Autobahn: https://github.com/crossbario/autobahn-python/commit/dd1cff8f9480a125e510108482bfaf5b9eedc916#diff-05ecf29bd3a5812b4f0b10f58ff172bbR32

**Comment by oberstet** [comment]
This is now enforced (select one framework only, right at the beginning):

```
(cpy351_1) oberstet@corei7ub1310:~/scm/crossbario/txaio$ python
Python 3.5.1 (default, Jan 22 2016, 12:36:22) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import txaio
>>> txaio.use_twisted()
>>> txaio.use_asyncio()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/scm/crossbario/txaio/txaio/__init__.py", line 112, in use_asyncio
    raise RuntimeError("Explicitly using '{}' already".format(_explicit_framework))
RuntimeError: Explicitly using 'twisted' already
>>> 
```

**Comment by abhigenie92** [comment]
Hi, I am still getting thee same issue:
Error:
```
Abhishek@ABHISHEK ~/Dropbox/abhishek_bhatia/notepad_app (master)
$ python __main__.py
[INFO              ] [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-04-26_5.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "__main__.py", line 19, in <module>
     from canvas.canvas_widget import CanvasWidget,RadioButton
   File "c:\Users\sony\Dropbox\abhishek_bhatia\notepad_app\canvas\canvas_widget.py", line 23, in <module>
     from network_comm.audio_client_tcp import AudioClientFactory
   File "c:\Users\sony\Dropbox\abhishek_bhatia\notepad_app\canvas\network_comm\audio_client_tcp.py", line 3, in <module>
     from autobahn.asyncio.websocket import WebSocketServerFactory
   File "c:\Users\sony\virtualenvs\noteapp\lib\site-packages\autobahn\asyncio\__init__.py", line 36, in <module>
     from autobahn.asyncio.websocket import \
   File "c:\Users\sony\virtualenvs\noteapp\lib\site-packages\autobahn\asyncio\websocket.py", line 32, in <module>
     txaio.use_asyncio()
   File "c:\Users\sony\virtualenvs\noteapp\lib\site-packages\txaio\__init__.py", line 117, in use_asyncio
     raise RuntimeError("Explicitly using '{}' already".format(_explicit_framework))
 RuntimeError: Explicitly using 'twisted' already
(noteapp)
```
Code:
```
import txaio
txaio.use_twisted()
#from twisted.internet.protocol import ClientFactory
import pdb,json
from autobahn.asyncio.websocket import WebSocketServerFactory
#from twisted.protocols.basic import NetstringReceiver
from twisted.internet.defer import inlineCallbacks
from twisted.internet.threads import deferToThread
from twisted.internet.defer import DeferredQueue

# audio imports
import pyaudio,wave,threading
from Queue import Queue
class AudioClient(NetstringReceiver):
	#audio parameters
	CHUNK = 1024
	FORMAT = pyaudio.paInt16
	CHANNELS = 1

## initialisation
	def __init__(self,factory,canvas_obj):
		'''initiates with factory and canvas object
		Reasons:
			factory:
			canvas object:
		'''
		self.factory = factory
		self.canvas_obj=canvas_obj
		
	def connectionMade(self):
		'''sends the username of the client to register the protocol at remore server with corresponding
		address'''
		print "Connected to audio remote server"
		self.sendString(json.dumps({'username':self.factory.username}))
		# start recording and sending audio
		if self.factory.canvas_obj.allow_all or self.factory.canvas_obj.client_state=='server' \
			or self.factory.canvas_obj.client_audio_send:
			self.start_audio_stream()
		# start receiving and playing audio
		self.receive_audio_stream()

## record and send
	def start_audio_stream(self):
		'''creates an audio stream for sending data
		A callback is defined on send_audio_data() to send the stream
		'''
		# create PyAudio Object
		self.send_stream_Pyobj=pyaudio.PyAudio()
		self.send_rate=int(self.send_stream_Pyobj.get_device_info_by_index(0)['defaultSampleRate']/4)
		# create stream
		self.send_stream=self.send_stream_Pyobj.open(format=self.FORMAT,channels=self.CHANNELS,
			rate=self.send_rate,input=True,frames_per_buffer=self.CHUNK,output=False)
		# start the stream
		self.send_stream.start_stream()
		self.send_audio_data_thread = threading.Thread(name='send_audio_data'\
			,target=self.send_audio_data)
		self.send_audio_data_thread.daemon=True
		self.send_audio_data_thread.start()	

	@inlineCallbacks 
	def send_audio_data(self):
		'''sends the audio chunk to remote server as string'''
		while True:
			audio_data = yield self.send_stream.read(self.CHUNK)
			self.sendString(audio_data)

## receive and play
	def receive_audio_stream(self):
		''' 1. creates an audio stream for receiving data
			2. creates an audio queue
			3. initiates a thread for playing the received audio
		'''
		# create PyAudio Object
		self.receive_stream_Pyobj=pyaudio.PyAudio()
		self.receive_rate=int(self.receive_stream_Pyobj.get_device_info_by_index(0)['defaultSampleRate']/4)
		# create stream
		self.stream_receive = self.receive_stream_Pyobj.open(format=self.FORMAT,channels=self.CHANNELS,
				rate=self.receive_rate,output=True,input=False)
		# start the receiving stream
		self.stream_receive.start_stream()
		# create a queue which gets filled in from data received
		self.recv_audio_queue=Queue() # queue that stores the audio received
		# create and start the thread for playing the received audio
		self.play_audio_received_thread = threading.Thread(name='play_audio_received'\
			,target=self.play_audio_received)
		self.play_audio_received_thread.daemon=True
		self.play_audio_received_thread.start()		

	def stringReceived(self,data):
		'''appends the audio string received to queue(recv_audio_queue) which is played by 
		play_audio_received thread'''
		self.recv_audio_queue.put(data)

	def play_audio_received(self):
		while True:
			self.stream_receive.write(self.recv_audio_queue.get())
			#self.recv_audio_queue.task_done()

## close streams, terminate pyaudio objects and stop threads
	def connectionLost(self, reason):
		# close send audio if exists
		try:
			self.send_stream.stop_stream()
			self.send_stream.close()
			self.send_stream_Pyobj.terminate()
		except:
			print "Send audio stream and object doesn't exist"

		# close receive audio stream and thread
		try:
			self.stream_receive.stop_stream()
			self.stream_receive.close()
			self.receive_stream_Pyobj.terminate()
			self.play_audio_received_thread.stopped=True
		except:
			print "Receive audio stream and object doesn't exist"

		


class AudioClientFactory(ClientFactory):
	def __init__(self, canvas_obj,username):
		self.canvas_obj = canvas_obj
		self.username=username

	def buildProtocol(self, addr):
		self.protocol=AudioClient(self,self.canvas_obj)
		return self.protocol

					
if __name__ == '__main__':
	from twisted.internet import reactor
	reactor.connectTCP("127.0.0.1",3036,AudioClientFactory('junkcanvas_obj','something'))
	reactor.run()
```

**Comment by meejah** [comment]
Well, the error is correct: on line 2 you ``txaio.use_twisted()`` but a few lines later you're importing from ``autobahn.asyncio.*`` which isn't possible; you should be importing from ``autobahn.twisted.*`` if you're wanting the Twisted-based classes. Also, you shouldn't need to call ``txaio.use_*()`` at all -- just import the correct autobahn package (they call ``.use_twisted()`` or ``.use_asyncio()`` as appropriate).

**Comment by abhigenie92** [comment]
@meejah Thanks for the reply! Changing the line to 
`from autobahn.asyncio.websocket import WebSocketServerFactory
`to 
`from autobahn.twisted.websocket import WebSocketServerFactory
`
I get the following error:
```
$ python audio_client_tcp.py
Traceback (most recent call last):
  File "audio_client_tcp.py", line 128, in <module>
    reactor.connectTCP("127.0.0.1",3036,AudioClientFactory('junkcanvas_obj','something'))
  File "c:\Users\sony\virtualenvs\noteapp\lib\site-packages\twisted\internet\posixbase.py", line 483, in connectTCP
    c.connect()
  File "c:\Users\sony\virtualenvs\noteapp\lib\site-packages\twisted\internet\base.py", line 1046, in connect
    self.factory.doStart()
AttributeError: 'AudioClientFactory' object has no attribute 'doStart'
(noteapp)
```

Complete code:
```
import pdb,json
from autobahn.twisted.websocket import WebSocketClientProtocol, \
    WebSocketClientFactory
from twisted.internet.defer import inlineCallbacks
from twisted.internet.threads import deferToThread
from twisted.internet.defer import DeferredQueue

# audio imports
import pyaudio,wave,threading
from Queue import Queue
class AudioClient(WebSocketClientFactory):
	#audio parameters
	CHUNK = 1024
	FORMAT = pyaudio.paInt16
	CHANNELS = 1

## initialisation
	def __init__(self,factory,canvas_obj):
		'''initiates with factory and canvas object
		Reasons:
			factory:
			canvas object:
		'''
		self.factory = factory
		self.canvas_obj=canvas_obj
		
	def connectionMade(self):
		'''sends the username of the client to register the protocol at remore server with corresponding
		address'''
		print "Connected to audio remote server"
		self.sendString(json.dumps({'username':self.factory.username}))
		# start recording and sending audio
		if self.factory.canvas_obj.allow_all or self.factory.canvas_obj.client_state=='server' \
			or self.factory.canvas_obj.client_audio_send:
			self.start_audio_stream()
		# start receiving and playing audio
		self.receive_audio_stream()

## record and send
	def start_audio_stream(self):
		'''creates an audio stream for sending data
		A callback is defined on send_audio_data() to send the stream
		'''
		# create PyAudio Object
		self.send_stream_Pyobj=pyaudio.PyAudio()
		self.send_rate=int(self.send_stream_Pyobj.get_device_info_by_index(0)['defaultSampleRate']/4)
		# create stream
		self.send_stream=self.send_stream_Pyobj.open(format=self.FORMAT,channels=self.CHANNELS,
			rate=self.send_rate,input=True,frames_per_buffer=self.CHUNK,output=False)
		# start the stream
		self.send_stream.start_stream()
		self.send_audio_data_thread = threading.Thread(name='send_audio_data'\
			,target=self.send_audio_data)
		self.send_audio_data_thread.daemon=True
		self.send_audio_data_thread.start()	

	@inlineCallbacks 
	def send_audio_data(self):
		'''sends the audio chunk to remote server as string'''
		while True:
			audio_data = yield self.send_stream.read(self.CHUNK)
			self.sendString(audio_data)

## receive and play
	def receive_audio_stream(self):
		''' 1. creates an audio stream for receiving data
			2. creates an audio queue
			3. initiates a thread for playing the received audio
		'''
		# create PyAudio Object
		self.receive_stream_Pyobj=pyaudio.PyAudio()
		self.receive_rate=int(self.receive_stream_Pyobj.get_device_info_by_index(0)['defaultSampleRate']/4)
		# create stream
		self.stream_receive = self.receive_stream_Pyobj.open(format=self.FORMAT,channels=self.CHANNELS,
				rate=self.receive_rate,output=True,input=False)
		# start the receiving stream
		self.stream_receive.start_stream()
		# create a queue which gets filled in from data received
		self.recv_audio_queue=Queue() # queue that stores the audio received
		# create and start the thread for playing the received audio
		self.play_audio_received_thread = threading.Thread(name='play_audio_received'\
			,target=self.play_audio_received)
		self.play_audio_received_thread.daemon=True
		self.play_audio_received_thread.start()		

	def stringReceived(self,data):
		'''appends the audio string received to queue(recv_audio_queue) which is played by 
		play_audio_received thread'''
		self.recv_audio_queue.put(data)

	def play_audio_received(self):
		while True:
			self.stream_receive.write(self.recv_audio_queue.get())
			#self.recv_audio_queue.task_done()

## close streams, terminate pyaudio objects and stop threads
	def connectionLost(self, reason):
		# close send audio if exists
		try:
			self.send_stream.stop_stream()
			self.send_stream.close()
			self.send_stream_Pyobj.terminate()
		except:
			print "Send audio stream and object doesn't exist"

		# close receive audio stream and thread
		try:
			self.stream_receive.stop_stream()
			self.stream_receive.close()
			self.receive_stream_Pyobj.terminate()
			self.play_audio_received_thread.stopped=True
		except:
			print "Receive audio stream and object doesn't exist"
			

class AudioClientFactory(WebSocketClientProtocol):
	def __init__(self, canvas_obj,username):
		self.canvas_obj = canvas_obj
		self.username=username

	def buildProtocol(self, addr):
		self.protocol=AudioClient(self,self.canvas_obj)
		return self.protocol
		
if __name__ == '__main__':
	from twisted.internet import reactor
	reactor.connectTCP("127.0.0.1",3036,AudioClientFactory('junkcanvas_obj','something'))
	reactor.run()
```

**Comment by meejah** [comment]
Can you please ask on either a Twisted mailing-list or the Crossbar.io one? https://groups.google.com/forum/#!forum/crossbario This really doesn't have anything to do with this ticket.

You're subclassing from a ``*Protocol`` but calling it a ``Factory``, which it isn't.
