### ISSUE TITLE
txaio std lib logging

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/txaio#75]
Please see https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/autobahnws/vxb4e03IUOQ
``` python
# Name would allow for _TxaioLogWrapper to not call std lib logging.getLogger with no name thus defaulting to root logging instance 
def make_logger(name=None):
    logger = _TxaioLogWrapper(logging.getLogger(name))
    # remember this so we can set their levels properly once
    # start_logging is actually called
    _loggers.add(logger)
    return logger


def start_logging(name=None, out=_stdout, level='info'):
    """
    Begin logging.

    :param out: if provided, a file-like object to log to. By default, this is
                stdout.
    :param level: the maximum log-level to emit (a string)
    """
    global _log_level, _loggers, _started_logging     ****** I tried setting log level to "none" and that passes this test but isn't implemented and throws another error
    if level not in log_levels:
        raise RuntimeError(
            "Invalid log level '{0}'; valid are: {1}".format(
                level, ', '.join(log_levels)
            )
        )

    if _started_logging:
        return

    _started_logging = True
    _log_level = level

    handler = _TxaioFileHandler(out)
    logging.getLogger(name).addHandler(handler)   ****** Name here too so that root logger isn't used
    # note: Don't need to call basicConfig() or similar, because we've
    # now added at least one handler to the root logger
    logging.raiseExceptions = True  # FIXME
    level_to_stdlib = {
        'critical': logging.CRITICAL,
        'error': logging.ERROR,
        'warn': logging.WARNING,
        'info': logging.INFO,
        'debug': logging.DEBUG,
        'trace': logging.DEBUG,
    }
    logging.getLogger(name).setLevel(level_to_stdlib[level])   ****** Name here too so that root logger isn't used
    # make sure any loggers we created before now have their log-level
    # set (any created after now will get it from _log_level
    for logger in _loggers:
        logger._set_log_level(level)
```

Maybe even better we could pass a std lib logging instance into make_logger, in case we are already using the root logger instance?

**Comment by singlecheeze** [comment]
Also this:
``` text
Traceback (most recent call last):
  File "/home/dave/PycharmProjects/monocle/backend/backend.py", line 1716, in <module>
    txaio.start_logging(level='none')
  File "/usr/lib/python3.5/site-packages/txaio/aio.py", line 222, in start_logging
    logging.getLogger().setLevel(level_to_stdlib[level])
KeyError: 'none'
```

The first check passes but lookup dict for std lib logging does not include the "none" log level:
``` python
def start_logging(out=_stdout, level='info'):
    """
    Begin logging.

    :param out: if provided, a file-like object to log to. By default, this is
                stdout.
    :param level: the maximum log-level to emit (a string)
    """
    global _log_level, _loggers, _started_logging
    if level not in log_levels:
        raise RuntimeError(
            "Invalid log level '{0}'; valid are: {1}".format(
                level, ', '.join(log_levels)
            )
        )
```

**Comment by meejah** [comment]
Maybe what we really want is similar "magic" to the ``tx`` side, which detects e.g. the local namespace to give to the logger (so that every call-site creating a logger doesn't have to invent a name). In any case, the ``aio`` implementation isn't consistent with the ``tx`` one.

**Comment by meejah** [comment]
Also, just to be clear: neither txaio nor Autobahn is "magically" starting logging -- using ApplicationRunner does call ``txaio.start_logging()`` as it's the "easy" interface and if nobody has started logging, then it's very confusing -- so I'd almost say this is at least partially an Autobahn bug: namely that the "run my component" API needs some way to say whether you want logging started for you or not.

I think the other ask here is that if Autobahn is using asyncio/stdlib logging then the name of the logger should be "something" (not None) so that if you choose to start logging yourself you have some control over what this part of the logging does. Likely this would take some more support code from txaio, but the real feature here is an Autobahn one (see https://github.com/crossbario/autobahn-python/issues/674 which I just filed to track these desires).

**Comment by singlecheeze** [comment]
Thank you @meejah!
